[project]
name = "pai-hidden-grasp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mink>=1.3.0",
    "mujoco>=3.14.0",
    "numpy>=2.4.6",
    "pillow>=12.3.0",
]

[project.scripts]
pai-hidden-grasp = "pai_hidden_grasp:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
